# Generated by Django 3.1.3 on 2020-12-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('imageurl', models.CharField(max_length=255)),
                ('userid', models.IntegerField()),
                ('send_timstamp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
